name: "Artifact and Release"

inputs:
  os:
    required: true
  arch:
    required: true

runs:
  using: "composite"
  steps:
    - name: Prepare artifacts
      shell: bash
      run: |
        cd sdk/build/out
        7z a "geniex-bridge.zip" ./*
        mv "geniex-bridge.zip" ../../..

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v5
      with:
        name: geniex-bridge-${{ inputs.os }}-${{ inputs.arch }}
        path: |
          sdk/geniex-bridge.zip
        retention-days: 14
